version: '3'
services:
  web:
    # restart: on-failure
    restart: always
    # build: .
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      NODE_ENV: production
