version: '3'
services:
  web:
    # restart: on-failure
    restart: always
    # build: .
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      NODE_ENV: prod
